name: CRT-Service PR
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Run tests
        run: npm test
